name: Docker Image CI of GHCR
description: Docker Image CI of GHCR by Yuvaraja

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the Docker image
        run: |
          docker login -u ${{ github.actor }} -p ${{ secrets.GH_PAT }} ghcr.io
          docker build . --file dockerfile --tag ghcr.io/devley-devs/devley-license-ws:latest
          docker push ghcr.io/devley-devs/devley-license-ws:latest
